### ISSUE TITLE
Using my own account for greetings

### ISSUE THREAD

**Issue by themaroqa** [JJ/pr-greeting-action#15]
When the message appear in a PR it greats with my own github account instead of a generic "github-actions" account. 
Using the following action.

```
name: "PR Greeter"
on: [pull_request]

jobs:
  pr-greeter:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeter"
        uses: JJ/pr-greeting-action@releases/v0
        with:
          repo-token: ${{ secrets.GREETER_ACTION }}
          pr-message: "Hey **#** welcome to the repo"
```
